apiVersion: apps/v1
kind: Deployment
metadata:
  name: ledger-api
  namespace: payments
  labels:
    app: ledger-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ledger-api
  template:
    metadata:
      labels:
        app: ledger-api
    spec:
      serviceAccountName: ledger-api

      containers:
        - name: ledger-api
          image: ghcr.io/pranavshinde-sa/dodo-devsecops-assignment:a17685ac3caceda0a4d1f6aaa9237b4d192abc79
          imagePullPolicy: IfNotPresent

          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true

            capabilities:
              drop:
                - ALL

            seccompProfile:
              type: RuntimeDefault

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"

          envFrom:
            - configMapRef:
                name: ledger-api-config


          env:
            - name: STRIPE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: ledger-api-secret
                  key: STRIPE_API_KEY
    
            - name: DB_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: ledger-api-secret
                  key: DB_PASSWORD
          ports:
            - containerPort: 8080

          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
            successThreshold: 1

          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3


