---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ledger-api-secret
  namespace: payments
spec:
  encryptedData:
    DB_PASSWORD: AgA3e3FAE2Mju3OzFh2P9S9QECMrsr9bPE+EviDFI5dmPzpUxtGxDpwVdrnKNW70hoUFVY6lg8IT5wXHoMbvvpiXpZFgIvpV6WdCID4O4fr4ln9ju9yfeZPS/jHfkd0UWb7dZtzPc0uAnjn+SGmW53/g/RDePJX/G6SOyF+38aKwWzvmRNE5ASDn2QCYAJbJdMA/Kn4vz5Z8Qr4BbtXpkq8eaaKyL1NzpJ94Raoz8gQJi9oSrxKUWjv//ylj4OrFRW1RO9zZzODxtqAS/IRB+oesGJaQZ3EorFl6T6v3jR5TK1eFaisKIcBrwHEU0FDU1KBjtIQs0NyrMlQlHVuQUwO2wI9cpGcL9dMAvDg33yo2lcTQthpBT7vGkC10dvEiegn6RhAl1tcn8cuVDFmQx7dClRuoyoRwgDReyoTMIhqlSXo5H7TtVQcj4mylmL4619CcZbC1IZ2kGZEvUU4fKE3fBjGZxODWzIZ9CI8XjXTR3VlclrlgXWSRyfT5TCxao1AqFUBY14XRkgpZq7xWwM2Hzl9sR32FkWCKJs4IQRgiBf+4KBrM02bsYU99ao+KzFPmsaY2jIYUb4A3rkRv3gEwC8MQx4Hc1htZsL+BrZUTTdg2sjxEAVmNIK8fMIAdhUKgEjC6aa4RNrWNzQWU3BJk10W8j5+rNK9jwTrAjp9UvFJmP/d0aGJ61HOx7otQVv+MkIgOiXz9kmSmUQ==
    STRIPE_API_KEY: AgB27cksWAnzqri+MoYRlCrUTBRoLL6Gf3YAtsEof9J2L2W/ZY32aCEHaah3yTuKFgmmZnbXPVfo2iUmRTQaIauMOaz41f3sMegV5lGuGpTFd/QXfHQ1PybYTtVfSb+fDnZ9vnCFzzY4ILHKDwAv2ayXshMMwHfibbDsWQbQXNNh5TcXcGYJB03wPCTvR9EOb3tvIXJ/2PhZ+RiTGanefvDk3Z3PFJItP/kz4o8Pw6fZYdKBr4bRCEUGGFY7KJ17U82vTKOoFUG4fV7/4fhMNzS0oktHx5L010r8/drQ1hQeVta5XddEaXyDkRkbbEPfXtSzyQo9+U34R1SwY2wibx3yQS7bxYKntpM27w12FJ4TlyAiH9uFsWnW/0NB0rqNvzH2CJdyMLLAbNYftRxU4G167dGJVHbWA2fdvaENlq6M0/jwjDe206u5l8J5e/U+OrktT5Ynhz9MjKGrJ1qZUvI795UDeQFwUFw8LGpi6sGILS3s9bPCnlgqs53si1tFtxHWCDvRG+IRRbB5C6M68MvfiFwvhSjCnuIeCaYJwD6jPTYoP/OA1y4ogX8qFC11BYwCBGhPg1WKwpOi7gVIVyyyO3K1gFlmMqC/uk3KbLso9fbZitWceYrDcgPIUSBgudNw96Yqqi1ZRyR2z+77rhidsXFMarcvm2wYeDtHaxj0Fz8tRNf4wkyp41BMSvIlkifLByVDrgjEqtAIqFcB0Hz3Od03kJe2SRolEpAuMg==
  template:
    metadata:
      name: ledger-api-secret
      namespace: payments
    type: Opaque
