name: Build & Push Image

on:
  workflow_call:
    outputs:
      digest:
        description: Image digest
        value: ${{ jobs.build-push.outputs.digest }}   

permissions:
  contents: read
  packages: write

jobs:
  build-push:
    outputs:
      digest: ${{ steps.build.outputs.digest }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262

      - name: Login to GHCR
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Convert repository name to lowercase
        id: repo
        run: echo "repo=${GITHUB_REPOSITORY,,}" >> $GITHUB_OUTPUT

      - name: Build and Push Image
        id: build
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8
        with:
          context: ./app
          file: ./app/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ steps.repo.outputs.repo }}:latest
            ghcr.io/${{ steps.repo.outputs.repo }}:${{ github.sha }}