name: Trivy Dependency Scan

on:
  workflow_call:

permissions:
  contents: read

jobs:
  dependency-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262

      - name: Run Trivy Dependency Scan
        uses: aquasecurity/trivy-action@a9c7b0f06e461e9d4b4d1711f154ee024b8d7ab8
        with:
          scan-type: 'fs'
          scan-ref: '.'
          scanners: 'vuln'
          format: 'table'
          exit-code: '1'
          severity: 'HIGH,CRITICAL'