name: Devsecops Pipeline

on:
  push:
    branches:
      - main
      - task2-secure-cicd-supply-chain

  pull_request:
    branches:
      - main

  workflow_dispatch:

permissions:
  actions: read
  attestations: write
  contents: read
  packages: write
  id-token: write

jobs:
  semgrep:
    name: Semgrep Scan
    uses: ./.github/workflows/semgrep.yml

  gitleaks:
    name: Gitleaks Scan
    uses: ./.github/workflows/gitleaks.yml

  dependency:
    name: Dependency scan
    uses: ./.github/workflows/dependency-scan.yml

  trivy-image:
    name: Docker image scan
    uses: ./.github/workflows/image-scan.yml

  build-push:
    name: Build and push to GHCR
    uses: ./.github/workflows/build-push.yml

  cosign:
    name: Cosign image signing
    needs: build-push
    uses: ./.github/workflows/cosign.yml
    with:
      digest: ${{ needs.build-push.outputs.digest }}

  slsa:
    name: Generate SLSA Provenance
    needs: build-push
    uses: ./.github/workflows/slsa.yml
    with:
      digest: ${{ needs.build-push.outputs.digest }}

  gitops-cd:
    needs:
      - build-push
      - cosign
      - slsa
    permissions:
      contents: write
    uses: ./.github/workflows/gitops-cd.yml
    